# Coolify configuration for WordPress deployment
version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Database configuration
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      
      # WordPress configuration
      - WP_DEBUG=${WP_DEBUG:-false}
      - WP_DEBUG_LOG=${WP_DEBUG_LOG:-false}
      - WP_DEBUG_DISPLAY=${WP_DEBUG_DISPLAY:-false}
      
      # Security keys
      - AUTH_KEY=${AUTH_KEY}
      - SECURE_AUTH_KEY=${SECURE_AUTH_KEY}
      - LOGGED_IN_KEY=${LOGGED_IN_KEY}
      - NONCE_KEY=${NONCE_KEY}
      - AUTH_SALT=${AUTH_SALT}
      - SECURE_AUTH_SALT=${SECURE_AUTH_SALT}
      - LOGGED_IN_SALT=${LOGGED_IN_SALT}
      - NONCE_SALT=${NONCE_SALT}
      
      # WordPress URLs
      - WP_HOME=${WP_HOME}
      - WP_SITEURL=${WP_SITEURL}
      
      # Table prefix
      - TABLE_PREFIX=${TABLE_PREFIX:-wp_}
    
    volumes:
      - wordpress_data:/var/www/html/wp-content/uploads
      - wordpress_data:/var/www/html/wp-content/upgrade
    
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  wordpress_data:
