services:
  wordpress:
    build: .
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content:/var/www/html/wp-content
    restart: unless-stopped

volumes:
  wordpress_data:
